name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libssl-dev libreadline-dev zlib1g-dev

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          sudo PREFIX=/usr/local ./ruby-build/install.sh

      - name: Install Ruby
        run: |
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
          echo "export PATH=/opt/hostedtoolcache/Ruby/3.1.4/x64/bin:\$PATH" >> $GITHUB_ENV

      - name: Install Bundler
        run: |
          source $GITHUB_ENV
          gem install bundler

      - name: Install and Build 🔧
        run: |
          source $GITHUB_ENV
          npm install -g mermaid.cli
          bundle install
          bundle exec jekyll build

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site